Feature modal
grvsh02/design-system pull request #17
Opened 2022-09-10 06:04 UTC by yakatyansh

<img width="1248" alt="Screenshot 2022-09-10 at 11 33 25 AM" src="https://user-images.githubusercontent.com/90173866/189471425-4e13580f-e089-4b50-abed-7885b9094e44.png">

exit button not working, rest is ok

2022-09-10 06:31 UTC, grvsh02 requested changes

2022-09-10 06:31 UTC, grvsh02 commented on src/components/modal.tsx
> +                    <Button className="align-top align-right " iconProps={{icon: "CloseCircle",}}  size="base" onClick={onClose}/>
The close button should close the modal too. The close state needs to be implemented inside the modal itself.

2022-09-10 06:34 UTC, grvsh02 commented
![Screenshot_20220910120228](https://user-images.githubusercontent.com/50337734/189472252-0c515584-5dd5-4bb8-83da-f2f87282024c.png)

A professional modal example for you. :-)

2022-09-11 05:21 UTC, yakatyansh commented
https://user-images.githubusercontent.com/90173866/189513688-059d1270-2620-4541-a053-62cdb51f9297.mov

@grvsh02  need help

2022-09-13 08:19 UTC, closed without merging