added a textbox for searchbar
grvsh02/design-system pull request #21
Opened 2022-09-13 13:00 UTC by yakatyansh

fixes : #12 
<img width="922" alt="Screenshot 2022-09-13 at 6 30 23 PM" src="https://user-images.githubusercontent.com/90173866/189907612-da617ab3-cf28-47a5-9549-f5c39dd835b5.png">

2022-09-22 06:58 UTC, yakatyansh commented
<img width="1241" alt="Screenshot 2022-09-22 at 12 22 45 PM" src="https://user-images.githubusercontent.com/90173866/191678221-75dd65b8-959e-4d5c-a7f8-a6be63b7470e.png">

2022-09-22 11:30 UTC, grvsh02 requested changes

2022-09-22 11:30 UTC, grvsh02 commented on src/components/navBar.tsx
> +            <div>
give this div some width, w-2/3, or something. This will help you get a wider search bar

2022-09-22 11:30 UTC, grvsh02 commented on src/components/navBar.tsx
> +    // @ts-ignore
bad practice

2022-09-22 11:30 UTC, grvsh02 commented on src/components/navBar.tsx
> +    border: 1px solid ${props  => props.border};
if you are passing a hard-coded border color, y giving it down the props ?? and even if you are doing so, make it dynamic, when the div is focused change the color using these props

2022-09-22 11:30 UTC, grvsh02 commented on src/components/navBar.tsx
> +    font-family: Pangram, sans-serif;
add some border radius

2022-09-26 15:52 UTC, yakatyansh commented
<img width="1053" alt="Screenshot 2022-09-26 at 9 22 35 PM" src="https://user-images.githubusercontent.com/90173866/192323221-db9e722b-f5c1-42f9-a154-c0e3aae5bad4.png">

2022-09-26 16:50 UTC, yakatyansh commented
https://user-images.githubusercontent.com/90173866/192334911-d0e605cd-eaef-4b6f-8cef-935aa51633d3.mov

2022-09-26 17:58 UTC, grvsh02 approved these changes

2022-09-26 17:58 UTC, grvsh02 commented on src/components/navBar.tsx
> +    width: 100%;/
??

2022-09-26 18:00 UTC, yakatyansh commented on src/components/navBar.tsx
> +    width: 100%;/
Typing error 😅

2022-10-15 08:28 UTC, merged